title: Karteek Menda
logo: /Blog_Images/Image.jpg
email: karteekmenda@gmail.com
description: Portolio Website

# Social Profiles
github_username: KarteekMenda93
linkedin_username: karteek-menda 

#[Linkedin](https://www.linkedin.com/in/karteek-menda/)
#- [medium](https://medium.com/@karteekmenda93)
#- [Github](https://github.com/KarteekMenda93)
#- [Twitter](https://twitter.com/KarteekMenda93)

#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0    #hacker@v0.2.0 #minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal  ## for minimal theme
