title: Karteek Menda
logo: /Blog_Images/Image.jpg
email: karteekmenda@gmail.com
description: Portolio Website

# Social Profiles
github_username: KarteekMenda93
linkedin_username: karteek-menda 

#[Linkedin](https://www.linkedin.com/in/karteek-menda/)
#- [medium](https://medium.com/@karteekmenda93)
#- [Github](https://github.com/KarteekMenda93)
#- [Twitter](https://twitter.com/KarteekMenda93)

# show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0    #hacker@v0.2.0 #minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal  ## for minimal theme

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://linkedin.com/in/karteek-menda" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="karteek-menda" height="30" width="40" /></a>
<a href="https://medium.com/@karteekmenda93" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/medium.svg" alt="@karteekmenda93" height="30" width="40" /></a>
<a href="https://github.com/KarteekMenda93" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/github.svg" alt="KarteekMenda93" height="30" width="40" /></a>
<a href="https://stackoverflow.com/users/11484165" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/stack-overflow.svg" alt="11484165" height="30" width="40" /></a>
<a href="https://twitter.com/KarteekMenda93" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="@KarteekMenda93" height="30" width="40" /></a>
<a href="https://karteekmenda93.github.io/portfolio/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/github.svg" alt="KarteekMenda93" height="30" width="40" /></a>
</p>
