title: Karteek Menda
logo: /Blog_Images/Image.jpg
description: Robotics Grad Student @ASU, Ex - Data Science Professional, Machine Learning Blogger
#show_downloads: true
#theme: jekyll-theme-minimal
theme: cayman
