title: Karteek Menda
logo: /Blog_Images/Image.jpg
description: Robotics Grad Student @ASU, Ex - Data Science Professional, Machine Learning Blogger
#show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
