title: Karteek Menda
logo: /Blog_Images/Image.jpg
description: Robotics and Autonomous System Masters Student, Ex - Data Science Professional, Machine Learning Blogger
show_downloads: true
theme: jekyll-theme-minimal
