title: Karteek Menda
logo: /Blog_Images/Image.jpg
description: Portolio Website
#show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0 #minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal  ## for minimal theme
