title: Karteek Menda
#logo: /assets/img/headshot_circle.png
description: Robotics and Autonomous System Masters Student, Ex - Data Science Professional, Machine Learning Blogger
show_downloads: true
theme: jekyll-theme-minimal
